root = "."
testdata_dir = "testdata"
tmp_dir = "bin"

[build]
args_bin = []
bin = "./bin/everato"
cmd = "go build -o ./bin/everato -tags=dev ."
delay = 1000
exclude_dir = [
    "assets",
    "vendor",
    "testdata",
    "logs",
    "www/dist",
    "www/node_modules",
]
exclude_file = []
exclude_regex = ["_test.go", ".log", "www/dist"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "html", "css", "tsx", "ts", "js", "json", "md"]
include_file = []
kill_delay = "0s"
log = "./logs/build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = ["cd www && pnpm build && cd .."]
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = "blue"
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = false

[proxy]
app_port = 8080
enabled = true
proxy_port = 9090

[screen]
clear_on_rebuild = false
keep_scroll = true
