// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking_query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBooking = `-- name: CancelBooking :one
UPDATE bookings
SET status = 'CANCELLED', deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, event_id, user_id, coupon_id, status, created_at, updated_at, total_amount, discount_amount, final_amount, coupon_code, notes, deleted_at
`

func (q *Queries) CancelBooking(ctx context.Context, id pgtype.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, cancelBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.CouponID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.FinalAmount,
		&i.CouponCode,
		&i.Notes,
		&i.DeletedAt,
	)
	return i, err
}

const countBookingsByEvent = `-- name: CountBookingsByEvent :one
SELECT COUNT(*) as count FROM bookings
WHERE event_id = $1 AND status != 'CANCELLED' AND deleted_at IS NULL
`

func (q *Queries) CountBookingsByEvent(ctx context.Context, eventID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBookingsByEvent, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBooking = `-- name: CreateBooking :one

INSERT INTO bookings (
    id,
    user_id,
    event_id,
    total_amount,
    status,
    coupon_code,
    discount_amount,
    final_amount,
    created_at,
    updated_at
) VALUES (
    $1,  -- id
    $2,  -- user_id
    $3,  -- event_id
    $4,  -- total_amount
    $5,  -- status
    $6,  -- coupon_code
    $7,  -- discount_amount
    $8,  -- final_amount
    CURRENT_TIMESTAMP,  -- created_at
    CURRENT_TIMESTAMP   -- updated_at
) RETURNING id, event_id, user_id, coupon_id, status, created_at, updated_at, total_amount, discount_amount, final_amount, coupon_code, notes, deleted_at
`

type CreateBookingParams struct {
	ID             pgtype.UUID    `json:"id"`
	UserID         pgtype.UUID    `json:"user_id"`
	EventID        pgtype.UUID    `json:"event_id"`
	TotalAmount    pgtype.Numeric `json:"total_amount"`
	Status         BookingStatus  `json:"status"`
	CouponCode     pgtype.Text    `json:"coupon_code"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	FinalAmount    pgtype.Numeric `json:"final_amount"`
}

// Booking Operations
func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.ID,
		arg.UserID,
		arg.EventID,
		arg.TotalAmount,
		arg.Status,
		arg.CouponCode,
		arg.DiscountAmount,
		arg.FinalAmount,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.CouponID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.FinalAmount,
		&i.CouponCode,
		&i.Notes,
		&i.DeletedAt,
	)
	return i, err
}

const createBookingTicket = `-- name: CreateBookingTicket :one

INSERT INTO booking_tickets (
    id,
    booking_id,
    ticket_type_id,
    quantity,
    price_per_unit,
    subtotal,
    created_at
) VALUES (
    $1,  -- id
    $2,  -- booking_id
    $3,  -- ticket_type_id
    $4,  -- quantity
    $5,  -- price_per_unit
    $6,  -- subtotal
    CURRENT_TIMESTAMP  -- created_at
) RETURNING id, booking_id, ticket_type_id, quantity, price_per_unit, subtotal, created_at
`

type CreateBookingTicketParams struct {
	ID           pgtype.UUID    `json:"id"`
	BookingID    pgtype.UUID    `json:"booking_id"`
	TicketTypeID pgtype.UUID    `json:"ticket_type_id"`
	Quantity     int32          `json:"quantity"`
	PricePerUnit pgtype.Numeric `json:"price_per_unit"`
	Subtotal     pgtype.Numeric `json:"subtotal"`
}

// Booking Ticket Operations
func (q *Queries) CreateBookingTicket(ctx context.Context, arg CreateBookingTicketParams) (BookingTicket, error) {
	row := q.db.QueryRow(ctx, createBookingTicket,
		arg.ID,
		arg.BookingID,
		arg.TicketTypeID,
		arg.Quantity,
		arg.PricePerUnit,
		arg.Subtotal,
	)
	var i BookingTicket
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.PricePerUnit,
		&i.Subtotal,
		&i.CreatedAt,
	)
	return i, err
}

const decrementTicketAvailability = `-- name: DecrementTicketAvailability :one
UPDATE ticket_types
SET available_tickets = available_tickets - $2
WHERE id = $1 AND available_tickets >= $2
RETURNING id, name, event_id, price, available_tickets
`

type DecrementTicketAvailabilityParams struct {
	ID               pgtype.UUID `json:"id"`
	AvailableTickets int32       `json:"available_tickets"`
}

func (q *Queries) DecrementTicketAvailability(ctx context.Context, arg DecrementTicketAvailabilityParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, decrementTicketAvailability, arg.ID, arg.AvailableTickets)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventID,
		&i.Price,
		&i.AvailableTickets,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, event_id, user_id, coupon_id, status, created_at, updated_at, total_amount, discount_amount, final_amount, coupon_code, notes, deleted_at FROM bookings
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBookingByID(ctx context.Context, id pgtype.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.CouponID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.FinalAmount,
		&i.CouponCode,
		&i.Notes,
		&i.DeletedAt,
	)
	return i, err
}

const getBookingTicketsByBookingID = `-- name: GetBookingTicketsByBookingID :many
SELECT bt.id, bt.booking_id, bt.ticket_type_id, bt.quantity, bt.price_per_unit, bt.subtotal, bt.created_at, tt.name as ticket_type_name
FROM booking_tickets bt
JOIN ticket_types tt ON bt.ticket_type_id = tt.id
WHERE bt.booking_id = $1
`

type GetBookingTicketsByBookingIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	BookingID      pgtype.UUID        `json:"booking_id"`
	TicketTypeID   pgtype.UUID        `json:"ticket_type_id"`
	Quantity       int32              `json:"quantity"`
	PricePerUnit   pgtype.Numeric     `json:"price_per_unit"`
	Subtotal       pgtype.Numeric     `json:"subtotal"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	TicketTypeName string             `json:"ticket_type_name"`
}

func (q *Queries) GetBookingTicketsByBookingID(ctx context.Context, bookingID pgtype.UUID) ([]GetBookingTicketsByBookingIDRow, error) {
	rows, err := q.db.Query(ctx, getBookingTicketsByBookingID, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookingTicketsByBookingIDRow
	for rows.Next() {
		var i GetBookingTicketsByBookingIDRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.TicketTypeID,
			&i.Quantity,
			&i.PricePerUnit,
			&i.Subtotal,
			&i.CreatedAt,
			&i.TicketTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingsByEvent = `-- name: GetBookingsByEvent :many
SELECT b.id, b.event_id, b.user_id, b.coupon_id, b.status, b.created_at, b.updated_at, b.total_amount, b.discount_amount, b.final_amount, b.coupon_code, b.notes, b.deleted_at, u.email as user_email, u.first_name, u.last_name
FROM bookings b
JOIN users u ON b.user_id = u.id
WHERE b.event_id = $1 AND b.deleted_at IS NULL
ORDER BY b.created_at DESC
`

type GetBookingsByEventRow struct {
	ID             pgtype.UUID        `json:"id"`
	EventID        pgtype.UUID        `json:"event_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	CouponID       pgtype.UUID        `json:"coupon_id"`
	Status         BookingStatus      `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	TotalAmount    pgtype.Numeric     `json:"total_amount"`
	DiscountAmount pgtype.Numeric     `json:"discount_amount"`
	FinalAmount    pgtype.Numeric     `json:"final_amount"`
	CouponCode     pgtype.Text        `json:"coupon_code"`
	Notes          pgtype.Text        `json:"notes"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	UserEmail      string             `json:"user_email"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
}

func (q *Queries) GetBookingsByEvent(ctx context.Context, eventID pgtype.UUID) ([]GetBookingsByEventRow, error) {
	rows, err := q.db.Query(ctx, getBookingsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookingsByEventRow
	for rows.Next() {
		var i GetBookingsByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.CouponID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalAmount,
			&i.DiscountAmount,
			&i.FinalAmount,
			&i.CouponCode,
			&i.Notes,
			&i.DeletedAt,
			&i.UserEmail,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventTicketAvailability = `-- name: GetEventTicketAvailability :many
SELECT
    tt.id,
    tt.name,
    tt.price,
    tt.available_tickets as total_available,
    tt.available_tickets - COALESCE(SUM(bt.quantity), 0) as remaining
FROM ticket_types tt
LEFT JOIN booking_tickets bt ON bt.ticket_type_id = tt.id
LEFT JOIN bookings b ON bt.booking_id = b.id AND b.status != 'CANCELLED' AND b.deleted_at IS NULL
WHERE tt.event_id = $1
GROUP BY tt.id, tt.name, tt.price, tt.available_tickets
ORDER BY tt.price ASC
`

type GetEventTicketAvailabilityRow struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	Price          float64     `json:"price"`
	TotalAvailable int32       `json:"total_available"`
	Remaining      int32       `json:"remaining"`
}

func (q *Queries) GetEventTicketAvailability(ctx context.Context, eventID pgtype.UUID) ([]GetEventTicketAvailabilityRow, error) {
	rows, err := q.db.Query(ctx, getEventTicketAvailability, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventTicketAvailabilityRow
	for rows.Next() {
		var i GetEventTicketAvailabilityRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.TotalAvailable,
			&i.Remaining,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketAvailability = `-- name: GetTicketAvailability :one
SELECT
    tt.id,
    tt.name,
    tt.price,
    tt.available_tickets as total_available,
    tt.available_tickets - COALESCE(SUM(bt.quantity), 0) as remaining
FROM ticket_types tt
LEFT JOIN booking_tickets bt ON bt.ticket_type_id = tt.id
LEFT JOIN bookings b ON bt.booking_id = b.id AND b.status != 'CANCELLED' AND b.deleted_at IS NULL
WHERE tt.id = $1
GROUP BY tt.id, tt.name, tt.price, tt.available_tickets
`

type GetTicketAvailabilityRow struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	Price          float64     `json:"price"`
	TotalAvailable int32       `json:"total_available"`
	Remaining      int32       `json:"remaining"`
}

func (q *Queries) GetTicketAvailability(ctx context.Context, id pgtype.UUID) (GetTicketAvailabilityRow, error) {
	row := q.db.QueryRow(ctx, getTicketAvailability, id)
	var i GetTicketAvailabilityRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.TotalAvailable,
		&i.Remaining,
	)
	return i, err
}

const getUserBookingCountForEvent = `-- name: GetUserBookingCountForEvent :one
SELECT COUNT(*) as count FROM bookings
WHERE user_id = $1 AND event_id = $2 AND status != 'CANCELLED' AND deleted_at IS NULL
`

type GetUserBookingCountForEventParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	EventID pgtype.UUID `json:"event_id"`
}

func (q *Queries) GetUserBookingCountForEvent(ctx context.Context, arg GetUserBookingCountForEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUserBookingCountForEvent, arg.UserID, arg.EventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserBookings = `-- name: GetUserBookings :many
SELECT b.id, b.event_id, b.user_id, b.coupon_id, b.status, b.created_at, b.updated_at, b.total_amount, b.discount_amount, b.final_amount, b.coupon_code, b.notes, b.deleted_at, e.title as event_title, e.start_time as event_start_time, e.end_time as event_end_time
FROM bookings b
JOIN events e ON b.event_id = e.id
WHERE b.user_id = $1 AND b.deleted_at IS NULL
ORDER BY b.created_at DESC
`

type GetUserBookingsRow struct {
	ID             pgtype.UUID        `json:"id"`
	EventID        pgtype.UUID        `json:"event_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	CouponID       pgtype.UUID        `json:"coupon_id"`
	Status         BookingStatus      `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	TotalAmount    pgtype.Numeric     `json:"total_amount"`
	DiscountAmount pgtype.Numeric     `json:"discount_amount"`
	FinalAmount    pgtype.Numeric     `json:"final_amount"`
	CouponCode     pgtype.Text        `json:"coupon_code"`
	Notes          pgtype.Text        `json:"notes"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	EventTitle     string             `json:"event_title"`
	EventStartTime pgtype.Timestamptz `json:"event_start_time"`
	EventEndTime   pgtype.Timestamptz `json:"event_end_time"`
}

func (q *Queries) GetUserBookings(ctx context.Context, userID pgtype.UUID) ([]GetUserBookingsRow, error) {
	rows, err := q.db.Query(ctx, getUserBookings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserBookingsRow
	for rows.Next() {
		var i GetUserBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.CouponID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalAmount,
			&i.DiscountAmount,
			&i.FinalAmount,
			&i.CouponCode,
			&i.Notes,
			&i.DeletedAt,
			&i.EventTitle,
			&i.EventStartTime,
			&i.EventEndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementTicketAvailability = `-- name: IncrementTicketAvailability :one
UPDATE ticket_types
SET available_tickets = available_tickets + $2
WHERE id = $1
RETURNING id, name, event_id, price, available_tickets
`

type IncrementTicketAvailabilityParams struct {
	ID               pgtype.UUID `json:"id"`
	AvailableTickets int32       `json:"available_tickets"`
}

func (q *Queries) IncrementTicketAvailability(ctx context.Context, arg IncrementTicketAvailabilityParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, incrementTicketAvailability, arg.ID, arg.AvailableTickets)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventID,
		&i.Price,
		&i.AvailableTickets,
	)
	return i, err
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, event_id, user_id, coupon_id, status, created_at, updated_at, total_amount, discount_amount, final_amount, coupon_code, notes, deleted_at
`

type UpdateBookingStatusParams struct {
	ID     pgtype.UUID   `json:"id"`
	Status BookingStatus `json:"status"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingStatus, arg.ID, arg.Status)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.CouponID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.FinalAmount,
		&i.CouponCode,
		&i.Notes,
		&i.DeletedAt,
	)
	return i, err
}
