// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkin_query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttendance = `-- name: CreateAttendance :one

INSERT INTO attendance (
    id,
    ticket_id,
    event_id,
    checked_in_by,
    location,
    device_info,
    checked_in_at
) VALUES (
    $1,  -- id
    $2,  -- ticket_id
    $3,  -- event_id
    $4,  -- checked_in_by (super_user id)
    $5,  -- location (nullable)
    $6,  -- device_info (nullable)
    CURRENT_TIMESTAMP
) RETURNING id, ticket_id, event_id, checked_in_at, checked_in_by, location, device_info, created_at
`

type CreateAttendanceParams struct {
	ID          pgtype.UUID `json:"id"`
	TicketID    pgtype.UUID `json:"ticket_id"`
	EventID     pgtype.UUID `json:"event_id"`
	CheckedInBy pgtype.UUID `json:"checked_in_by"`
	Location    pgtype.Text `json:"location"`
	DeviceInfo  pgtype.Text `json:"device_info"`
}

// Check-in / Attendance Operations
// Records a successful check-in event.
func (q *Queries) CreateAttendance(ctx context.Context, arg CreateAttendanceParams) (Attendance, error) {
	row := q.db.QueryRow(ctx, createAttendance,
		arg.ID,
		arg.TicketID,
		arg.EventID,
		arg.CheckedInBy,
		arg.Location,
		arg.DeviceInfo,
	)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.EventID,
		&i.CheckedInAt,
		&i.CheckedInBy,
		&i.Location,
		&i.DeviceInfo,
		&i.CreatedAt,
	)
	return i, err
}

const getAttendanceByTicket = `-- name: GetAttendanceByTicket :one
SELECT id, ticket_id, event_id, checked_in_at, checked_in_by, location, device_info, created_at FROM attendance
WHERE ticket_id = $1
ORDER BY checked_in_at DESC
LIMIT 1
`

func (q *Queries) GetAttendanceByTicket(ctx context.Context, ticketID pgtype.UUID) (Attendance, error) {
	row := q.db.QueryRow(ctx, getAttendanceByTicket, ticketID)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.EventID,
		&i.CheckedInAt,
		&i.CheckedInBy,
		&i.Location,
		&i.DeviceInfo,
		&i.CreatedAt,
	)
	return i, err
}

const getEventAttendanceStats = `-- name: GetEventAttendanceStats :one
SELECT
    COUNT(DISTINCT t.id)              AS total_tickets,
    COUNT(DISTINCT a.ticket_id)       AS checked_in_count,
    COUNT(DISTINCT t.id) - COUNT(DISTINCT a.ticket_id) AS not_checked_in_count
FROM bookings b
JOIN tickets t   ON t.booking_id = b.id AND t.deleted_at IS NULL
LEFT JOIN attendance a ON a.ticket_id = t.id
WHERE b.event_id = $1
  AND b.deleted_at IS NULL
`

type GetEventAttendanceStatsRow struct {
	TotalTickets      int64 `json:"total_tickets"`
	CheckedInCount    int64 `json:"checked_in_count"`
	NotCheckedInCount int32 `json:"not_checked_in_count"`
}

// Returns check-in statistics for a given event.
func (q *Queries) GetEventAttendanceStats(ctx context.Context, eventID pgtype.UUID) (GetEventAttendanceStatsRow, error) {
	row := q.db.QueryRow(ctx, getEventAttendanceStats, eventID)
	var i GetEventAttendanceStatsRow
	err := row.Scan(&i.TotalTickets, &i.CheckedInCount, &i.NotCheckedInCount)
	return i, err
}

const getEventAttendees = `-- name: GetEventAttendees :many
SELECT
    t.id          AS ticket_id,
    t.ticket_number,
    t.is_checked_in,
    t.checked_in_at,
    u.email       AS user_email,
    u.first_name,
    u.last_name,
    tt.name       AS ticket_type_name
FROM bookings b
JOIN users u         ON u.id = b.user_id
JOIN tickets t       ON t.booking_id = b.id AND t.deleted_at IS NULL
JOIN ticket_types tt ON tt.id = t.ticket_type_id
WHERE b.event_id = $1
  AND b.deleted_at IS NULL
ORDER BY b.created_at ASC
`

type GetEventAttendeesRow struct {
	TicketID       pgtype.UUID        `json:"ticket_id"`
	TicketNumber   string             `json:"ticket_number"`
	IsCheckedIn    bool               `json:"is_checked_in"`
	CheckedInAt    pgtype.Timestamptz `json:"checked_in_at"`
	UserEmail      string             `json:"user_email"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	TicketTypeName string             `json:"ticket_type_name"`
}

// Lists all attendees (checked-in or not) for an event.
func (q *Queries) GetEventAttendees(ctx context.Context, eventID pgtype.UUID) ([]GetEventAttendeesRow, error) {
	rows, err := q.db.Query(ctx, getEventAttendees, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventAttendeesRow
	for rows.Next() {
		var i GetEventAttendeesRow
		if err := rows.Scan(
			&i.TicketID,
			&i.TicketNumber,
			&i.IsCheckedIn,
			&i.CheckedInAt,
			&i.UserEmail,
			&i.FirstName,
			&i.LastName,
			&i.TicketTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
