// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: event_query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEventsByStatus = `-- name: CountEventsByStatus :one
SELECT COUNT(*) as count FROM events
WHERE status = $1
`

func (q *Queries) CountEventsByStatus(ctx context.Context, status EventStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalEvents = `-- name: CountTotalEvents :one
SELECT COUNT(*) as total_events FROM events
`

func (q *Queries) CountTotalEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalEvents)
	var total_events int64
	err := row.Scan(&total_events)
	return total_events, err
}

const countUpcomingEvents = `-- name: CountUpcomingEvents :one
SELECT COUNT(*) as upcoming_events FROM events
WHERE start_time > CURRENT_TIMESTAMP
`

func (q *Queries) CountUpcomingEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUpcomingEvents)
	var upcoming_events int64
	err := row.Scan(&upcoming_events)
	return upcoming_events, err
}

const createCoupon = `-- name: CreateCoupon :one

INSERT INTO coupons (
    event_id,
    code,
    discount_percentage,
    valid_from,
    valid_until,
    usage_limit,
    usage_count
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    0
) RETURNING id, event_id, code, discount_percentage, valid_from, valid_until, usage_limit, created_at, updated_at, usage_count
`

type CreateCouponParams struct {
	EventID            pgtype.UUID        `json:"event_id"`
	Code               string             `json:"code"`
	DiscountPercentage float64            `json:"discount_percentage"`
	ValidFrom          pgtype.Timestamptz `json:"valid_from"`
	ValidUntil         pgtype.Timestamptz `json:"valid_until"`
	UsageLimit         int32              `json:"usage_limit"`
}

// Coupon Operations
func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, createCoupon,
		arg.EventID,
		arg.Code,
		arg.DiscountPercentage,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.UsageLimit,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Code,
		&i.DiscountPercentage,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.UsageLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsageCount,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    title,
    description,
    slug,
    banner,
    icon,
    admin_id,
    start_time,
    end_time,
    location,
    total_seats,
    available_seats,
    status,
    organizer_name,
    organizer_email,
    organizer_phone,
    organization,
    contact_email,
    contact_phone,
    refund_policy,
    terms_and_conditions,
    event_type,
    category,
    max_tickets_per_user,
    booking_start_time,
    booking_end_time,
    tags,
    website_url,
    facebook_url,
    twitter_url,
    instagram_url,
    linkedin_url,
    venue_name,
    address_line1,
    address_line2,
    city,
    state,
    postal_code,
    country,
    latitude,
    longitude,
    created_at,
    updated_at
) VALUES (
    $1,  -- title
    $2,  -- description
    $3,  -- slug
    $4,  -- banner
    $5,  -- icon
    $6,  -- admin_id
    $7,  -- start_time
    $8,  -- end_time
    $9,  -- location
    $10, -- total_seats
    $11, -- available_seats
    $12, -- status
    $13, -- organizer_name
    $14, -- organizer_email
    $15, -- organizer_phone
    $16, -- organization
    $17, -- contact_email
    $18, -- contact_phone
    $19, -- refund_policy
    $20, -- terms_and_conditions
    $21, -- event_type
    $22, -- category
    $23, -- max_tickets_per_user
    $24, -- booking_start_time
    $25, -- booking_end_time
    $26, -- tags
    $27, -- website_url
    $28, -- facebook_url
    $29, -- twitter_url
    $30, -- instagram_url
    $31, -- linkedin_url
    $32, -- venue_name
    $33, -- address_line1
    $34, -- address_line2
    $35, -- city
    $36, -- state
    $37, -- postal_code
    $38, -- country
    $39, -- latitude
    $40, -- longitude
    CURRENT_TIMESTAMP, -- created_at
    CURRENT_TIMESTAMP  -- updated_at
) RETURNING id, title, description, banner, icon, admin_id, start_time, end_time, location, total_seats, available_seats, created_at, updated_at, slug, status, organizer_name, organizer_email, organizer_phone, organization, contact_email, contact_phone, refund_policy, terms_and_conditions, event_type, category, max_tickets_per_user, booking_start_time, booking_end_time, tags, website_url, facebook_url, twitter_url, instagram_url, linkedin_url, venue_name, address_line1, address_line2, city, state, postal_code, country, latitude, longitude
`

type CreateEventParams struct {
	Title              string             `json:"title"`
	Description        string             `json:"description"`
	Slug               string             `json:"slug"`
	Banner             string             `json:"banner"`
	Icon               string             `json:"icon"`
	AdminID            pgtype.UUID        `json:"admin_id"`
	StartTime          pgtype.Timestamptz `json:"start_time"`
	EndTime            pgtype.Timestamptz `json:"end_time"`
	Location           pgtype.Text        `json:"location"`
	TotalSeats         int32              `json:"total_seats"`
	AvailableSeats     int32              `json:"available_seats"`
	Status             EventStatus        `json:"status"`
	OrganizerName      pgtype.Text        `json:"organizer_name"`
	OrganizerEmail     pgtype.Text        `json:"organizer_email"`
	OrganizerPhone     pgtype.Text        `json:"organizer_phone"`
	Organization       pgtype.Text        `json:"organization"`
	ContactEmail       pgtype.Text        `json:"contact_email"`
	ContactPhone       pgtype.Text        `json:"contact_phone"`
	RefundPolicy       pgtype.Text        `json:"refund_policy"`
	TermsAndConditions pgtype.Text        `json:"terms_and_conditions"`
	EventType          pgtype.Text        `json:"event_type"`
	Category           pgtype.Text        `json:"category"`
	MaxTicketsPerUser  pgtype.Int4        `json:"max_tickets_per_user"`
	BookingStartTime   pgtype.Timestamptz `json:"booking_start_time"`
	BookingEndTime     pgtype.Timestamptz `json:"booking_end_time"`
	Tags               []string           `json:"tags"`
	WebsiteUrl         pgtype.Text        `json:"website_url"`
	FacebookUrl        pgtype.Text        `json:"facebook_url"`
	TwitterUrl         pgtype.Text        `json:"twitter_url"`
	InstagramUrl       pgtype.Text        `json:"instagram_url"`
	LinkedinUrl        pgtype.Text        `json:"linkedin_url"`
	VenueName          pgtype.Text        `json:"venue_name"`
	AddressLine1       pgtype.Text        `json:"address_line1"`
	AddressLine2       pgtype.Text        `json:"address_line2"`
	City               pgtype.Text        `json:"city"`
	State              pgtype.Text        `json:"state"`
	PostalCode         pgtype.Text        `json:"postal_code"`
	Country            pgtype.Text        `json:"country"`
	Latitude           pgtype.Numeric     `json:"latitude"`
	Longitude          pgtype.Numeric     `json:"longitude"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Title,
		arg.Description,
		arg.Slug,
		arg.Banner,
		arg.Icon,
		arg.AdminID,
		arg.StartTime,
		arg.EndTime,
		arg.Location,
		arg.TotalSeats,
		arg.AvailableSeats,
		arg.Status,
		arg.OrganizerName,
		arg.OrganizerEmail,
		arg.OrganizerPhone,
		arg.Organization,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.RefundPolicy,
		arg.TermsAndConditions,
		arg.EventType,
		arg.Category,
		arg.MaxTicketsPerUser,
		arg.BookingStartTime,
		arg.BookingEndTime,
		arg.Tags,
		arg.WebsiteUrl,
		arg.FacebookUrl,
		arg.TwitterUrl,
		arg.InstagramUrl,
		arg.LinkedinUrl,
		arg.VenueName,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.Latitude,
		arg.Longitude,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Banner,
		&i.Icon,
		&i.AdminID,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.TotalSeats,
		&i.AvailableSeats,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.Status,
		&i.OrganizerName,
		&i.OrganizerEmail,
		&i.OrganizerPhone,
		&i.Organization,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.RefundPolicy,
		&i.TermsAndConditions,
		&i.EventType,
		&i.Category,
		&i.MaxTicketsPerUser,
		&i.BookingStartTime,
		&i.BookingEndTime,
		&i.Tags,
		&i.WebsiteUrl,
		&i.FacebookUrl,
		&i.TwitterUrl,
		&i.InstagramUrl,
		&i.LinkedinUrl,
		&i.VenueName,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const createTicketType = `-- name: CreateTicketType :one

INSERT INTO ticket_types (
    name,
    event_id,
    price,
    available_tickets
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, name, event_id, price, available_tickets
`

type CreateTicketTypeParams struct {
	Name             string      `json:"name"`
	EventID          pgtype.UUID `json:"event_id"`
	Price            float64     `json:"price"`
	AvailableTickets int32       `json:"available_tickets"`
}

// Ticket Type Operations
func (q *Queries) CreateTicketType(ctx context.Context, arg CreateTicketTypeParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, createTicketType,
		arg.Name,
		arg.EventID,
		arg.Price,
		arg.AvailableTickets,
	)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventID,
		&i.Price,
		&i.AvailableTickets,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getCouponsByEventID = `-- name: GetCouponsByEventID :many
SELECT id, event_id, code, discount_percentage, valid_from, valid_until, usage_limit, created_at, updated_at, usage_count FROM coupons
WHERE event_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCouponsByEventID(ctx context.Context, eventID pgtype.UUID) ([]Coupon, error) {
	rows, err := q.db.Query(ctx, getCouponsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coupon
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Code,
			&i.DiscountPercentage,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.UsageLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UsageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    COUNT(*) as total_events,
    COUNT(CASE WHEN status = 'CREATED' THEN 1 END) as created_events,
    COUNT(CASE WHEN status = 'STARTED' THEN 1 END) as active_events,
    COUNT(CASE WHEN status = 'COMPLETED' THEN 1 END) as completed_events,
    COUNT(CASE WHEN status = 'CANCELLED' THEN 1 END) as cancelled_events,
    COUNT(CASE WHEN start_time > CURRENT_TIMESTAMP THEN 1 END) as upcoming_events
FROM events
`

type GetDashboardStatsRow struct {
	TotalEvents     int64 `json:"total_events"`
	CreatedEvents   int64 `json:"created_events"`
	ActiveEvents    int64 `json:"active_events"`
	CompletedEvents int64 `json:"completed_events"`
	CancelledEvents int64 `json:"cancelled_events"`
	UpcomingEvents  int64 `json:"upcoming_events"`
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.TotalEvents,
		&i.CreatedEvents,
		&i.ActiveEvents,
		&i.CompletedEvents,
		&i.CancelledEvents,
		&i.UpcomingEvents,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, title, description, banner, icon, admin_id, start_time, end_time, location, total_seats, available_seats, created_at, updated_at, slug, status, organizer_name, organizer_email, organizer_phone, organization, contact_email, contact_phone, refund_policy, terms_and_conditions, event_type, category, max_tickets_per_user, booking_start_time, booking_end_time, tags, website_url, facebook_url, twitter_url, instagram_url, linkedin_url, venue_name, address_line1, address_line2, city, state, postal_code, country, latitude, longitude FROM events
WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Banner,
		&i.Icon,
		&i.AdminID,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.TotalSeats,
		&i.AvailableSeats,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.Status,
		&i.OrganizerName,
		&i.OrganizerEmail,
		&i.OrganizerPhone,
		&i.Organization,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.RefundPolicy,
		&i.TermsAndConditions,
		&i.EventType,
		&i.Category,
		&i.MaxTicketsPerUser,
		&i.BookingStartTime,
		&i.BookingEndTime,
		&i.Tags,
		&i.WebsiteUrl,
		&i.FacebookUrl,
		&i.TwitterUrl,
		&i.InstagramUrl,
		&i.LinkedinUrl,
		&i.VenueName,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getEventBySlug = `-- name: GetEventBySlug :one
SELECT id, title, description, banner, icon, admin_id, start_time, end_time, location, total_seats, available_seats, created_at, updated_at, slug, status, organizer_name, organizer_email, organizer_phone, organization, contact_email, contact_phone, refund_policy, terms_and_conditions, event_type, category, max_tickets_per_user, booking_start_time, booking_end_time, tags, website_url, facebook_url, twitter_url, instagram_url, linkedin_url, venue_name, address_line1, address_line2, city, state, postal_code, country, latitude, longitude FROM events
WHERE slug = $1
`

func (q *Queries) GetEventBySlug(ctx context.Context, slug string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventBySlug, slug)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Banner,
		&i.Icon,
		&i.AdminID,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.TotalSeats,
		&i.AvailableSeats,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.Status,
		&i.OrganizerName,
		&i.OrganizerEmail,
		&i.OrganizerPhone,
		&i.Organization,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.RefundPolicy,
		&i.TermsAndConditions,
		&i.EventType,
		&i.Category,
		&i.MaxTicketsPerUser,
		&i.BookingStartTime,
		&i.BookingEndTime,
		&i.Tags,
		&i.WebsiteUrl,
		&i.FacebookUrl,
		&i.TwitterUrl,
		&i.InstagramUrl,
		&i.LinkedinUrl,
		&i.VenueName,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getRecentEvents = `-- name: GetRecentEvents :many
SELECT id, title, description, banner, icon, admin_id, start_time, end_time, location, total_seats, available_seats, created_at, updated_at, slug, status, organizer_name, organizer_email, organizer_phone, organization, contact_email, contact_phone, refund_policy, terms_and_conditions, event_type, category, max_tickets_per_user, booking_start_time, booking_end_time, tags, website_url, facebook_url, twitter_url, instagram_url, linkedin_url, venue_name, address_line1, address_line2, city, state, postal_code, country, latitude, longitude FROM events
WHERE start_time >= CURRENT_TIMESTAMP - INTERVAL '1 day'
ORDER BY
    CASE
        WHEN start_time > CURRENT_TIMESTAMP THEN ABS(EXTRACT(EPOCH FROM (start_time - CURRENT_TIMESTAMP)))
        ELSE ABS(EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - start_time)))
    END ASC
LIMIT $1
`

func (q *Queries) GetRecentEvents(ctx context.Context, limit int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, getRecentEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Banner,
			&i.Icon,
			&i.AdminID,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.TotalSeats,
			&i.AvailableSeats,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.Status,
			&i.OrganizerName,
			&i.OrganizerEmail,
			&i.OrganizerPhone,
			&i.Organization,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.RefundPolicy,
			&i.TermsAndConditions,
			&i.EventType,
			&i.Category,
			&i.MaxTicketsPerUser,
			&i.BookingStartTime,
			&i.BookingEndTime,
			&i.Tags,
			&i.WebsiteUrl,
			&i.FacebookUrl,
			&i.TwitterUrl,
			&i.InstagramUrl,
			&i.LinkedinUrl,
			&i.VenueName,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketTypesByEventID = `-- name: GetTicketTypesByEventID :many
SELECT id, name, event_id, price, available_tickets FROM ticket_types
WHERE event_id = $1
ORDER BY price ASC
`

func (q *Queries) GetTicketTypesByEventID(ctx context.Context, eventID pgtype.UUID) ([]TicketType, error) {
	rows, err := q.db.Query(ctx, getTicketTypesByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketType
	for rows.Next() {
		var i TicketType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventID,
			&i.Price,
			&i.AvailableTickets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidCouponByCode = `-- name: GetValidCouponByCode :one
SELECT id, event_id, code, discount_percentage, valid_from, valid_until, usage_limit, created_at, updated_at, usage_count FROM coupons
WHERE code = $1
    AND valid_from <= CURRENT_TIMESTAMP
    AND valid_until >= CURRENT_TIMESTAMP
    AND usage_count < usage_limit
LIMIT 1
`

func (q *Queries) GetValidCouponByCode(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRow(ctx, getValidCouponByCode, code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Code,
		&i.DiscountPercentage,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.UsageLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsageCount,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, title, description, banner, icon, admin_id, start_time, end_time, location, total_seats, available_seats, created_at, updated_at, slug, status, organizer_name, organizer_email, organizer_phone, organization, contact_email, contact_phone, refund_policy, terms_and_conditions, event_type, category, max_tickets_per_user, booking_start_time, booking_end_time, tags, website_url, facebook_url, twitter_url, instagram_url, linkedin_url, venue_name, address_line1, address_line2, city, state, postal_code, country, latitude, longitude FROM events
    ORDER BY start_time DESC
LIMIT $1 OFFSET $2
`

type ListEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Banner,
			&i.Icon,
			&i.AdminID,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.TotalSeats,
			&i.AvailableSeats,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.Status,
			&i.OrganizerName,
			&i.OrganizerEmail,
			&i.OrganizerPhone,
			&i.Organization,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.RefundPolicy,
			&i.TermsAndConditions,
			&i.EventType,
			&i.Category,
			&i.MaxTicketsPerUser,
			&i.BookingStartTime,
			&i.BookingEndTime,
			&i.Tags,
			&i.WebsiteUrl,
			&i.FacebookUrl,
			&i.TwitterUrl,
			&i.InstagramUrl,
			&i.LinkedinUrl,
			&i.VenueName,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByAdmin = `-- name: ListEventsByAdmin :many
SELECT id, title, description, banner, icon, admin_id, start_time, end_time, location, total_seats, available_seats, created_at, updated_at, slug, status, organizer_name, organizer_email, organizer_phone, organization, contact_email, contact_phone, refund_policy, terms_and_conditions, event_type, category, max_tickets_per_user, booking_start_time, booking_end_time, tags, website_url, facebook_url, twitter_url, instagram_url, linkedin_url, venue_name, address_line1, address_line2, city, state, postal_code, country, latitude, longitude FROM events
    WHERE admin_id = $1
ORDER BY start_time DESC
`

func (q *Queries) ListEventsByAdmin(ctx context.Context, adminID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByAdmin, adminID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Banner,
			&i.Icon,
			&i.AdminID,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.TotalSeats,
			&i.AvailableSeats,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.Status,
			&i.OrganizerName,
			&i.OrganizerEmail,
			&i.OrganizerPhone,
			&i.Organization,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.RefundPolicy,
			&i.TermsAndConditions,
			&i.EventType,
			&i.Category,
			&i.MaxTicketsPerUser,
			&i.BookingStartTime,
			&i.BookingEndTime,
			&i.Tags,
			&i.WebsiteUrl,
			&i.FacebookUrl,
			&i.TwitterUrl,
			&i.InstagramUrl,
			&i.LinkedinUrl,
			&i.VenueName,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByName = `-- name: SearchByName :many
SELECT id, title, description, banner, icon, admin_id, start_time, end_time, location, total_seats, available_seats, created_at, updated_at, slug, status, organizer_name, organizer_email, organizer_phone, organization, contact_email, contact_phone, refund_policy, terms_and_conditions, event_type, category, max_tickets_per_user, booking_start_time, booking_end_time, tags, website_url, facebook_url, twitter_url, instagram_url, linkedin_url, venue_name, address_line1, address_line2, city, state, postal_code, country, latitude, longitude FROM events
    WHERE title ILIKE '%' || $1 || '%'
    OR description ILIKE '%' || $1 || '%'
    OR slug ILIKE '%' || $1 || '%'
    ORDER BY start_time DESC
LIMIT $2 OFFSET $3
`

type SearchByNameParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchByName(ctx context.Context, arg SearchByNameParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, searchByName, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Banner,
			&i.Icon,
			&i.AdminID,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.TotalSeats,
			&i.AvailableSeats,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.Status,
			&i.OrganizerName,
			&i.OrganizerEmail,
			&i.OrganizerPhone,
			&i.Organization,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.RefundPolicy,
			&i.TermsAndConditions,
			&i.EventType,
			&i.Category,
			&i.MaxTicketsPerUser,
			&i.BookingStartTime,
			&i.BookingEndTime,
			&i.Tags,
			&i.WebsiteUrl,
			&i.FacebookUrl,
			&i.TwitterUrl,
			&i.InstagramUrl,
			&i.LinkedinUrl,
			&i.VenueName,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSlug = `-- name: SearchSlug :one
SELECT slug FROM events
WHERE slug = $1
`

func (q *Queries) SearchSlug(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRow(ctx, searchSlug, slug)
	err := row.Scan(&slug)
	return slug, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET
    title = $2,
    description = $3,
    slug = $4,
    banner = $5,
    icon = $6,
    admin_id = $7,
    start_time = $8,
    end_time = $9,
    location = $10,
    total_seats = $11,
    available_seats = $12,
    status = $13,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, title, description, banner, icon, admin_id, start_time, end_time, location, total_seats, available_seats, created_at, updated_at, slug, status, organizer_name, organizer_email, organizer_phone, organization, contact_email, contact_phone, refund_policy, terms_and_conditions, event_type, category, max_tickets_per_user, booking_start_time, booking_end_time, tags, website_url, facebook_url, twitter_url, instagram_url, linkedin_url, venue_name, address_line1, address_line2, city, state, postal_code, country, latitude, longitude
`

type UpdateEventParams struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Slug           string             `json:"slug"`
	Banner         string             `json:"banner"`
	Icon           string             `json:"icon"`
	AdminID        pgtype.UUID        `json:"admin_id"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	Location       pgtype.Text        `json:"location"`
	TotalSeats     int32              `json:"total_seats"`
	AvailableSeats int32              `json:"available_seats"`
	Status         EventStatus        `json:"status"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Slug,
		arg.Banner,
		arg.Icon,
		arg.AdminID,
		arg.StartTime,
		arg.EndTime,
		arg.Location,
		arg.TotalSeats,
		arg.AvailableSeats,
		arg.Status,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Banner,
		&i.Icon,
		&i.AdminID,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.TotalSeats,
		&i.AvailableSeats,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.Status,
		&i.OrganizerName,
		&i.OrganizerEmail,
		&i.OrganizerPhone,
		&i.Organization,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.RefundPolicy,
		&i.TermsAndConditions,
		&i.EventType,
		&i.Category,
		&i.MaxTicketsPerUser,
		&i.BookingStartTime,
		&i.BookingEndTime,
		&i.Tags,
		&i.WebsiteUrl,
		&i.FacebookUrl,
		&i.TwitterUrl,
		&i.InstagramUrl,
		&i.LinkedinUrl,
		&i.VenueName,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const updateTicketTypeAvailability = `-- name: UpdateTicketTypeAvailability :one
UPDATE ticket_types
SET available_tickets = $2
WHERE id = $1
RETURNING id, name, event_id, price, available_tickets
`

type UpdateTicketTypeAvailabilityParams struct {
	ID               pgtype.UUID `json:"id"`
	AvailableTickets int32       `json:"available_tickets"`
}

func (q *Queries) UpdateTicketTypeAvailability(ctx context.Context, arg UpdateTicketTypeAvailabilityParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, updateTicketTypeAvailability, arg.ID, arg.AvailableTickets)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventID,
		&i.Price,
		&i.AvailableTickets,
	)
	return i, err
}
