// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTicketsForBooking = `-- name: CountTicketsForBooking :one
SELECT COUNT(*) AS count
FROM tickets
WHERE booking_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountTicketsForBooking(ctx context.Context, bookingID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTicketsForBooking, bookingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTicket = `-- name: CreateTicket :one

INSERT INTO tickets (
    id,
    booking_id,
    ticket_type_id,
    ticket_number,
    qr_code_data,
    qr_code_image,
    is_checked_in,
    created_at
) VALUES (
    $1,  -- id (UUID)
    $2,  -- booking_id
    $3,  -- ticket_type_id
    $4,  -- ticket_number  (e.g. "EVT-2026-00001")
    $5,  -- qr_code_data   (HMAC-signed JSON string)
    $6,  -- qr_code_image  (base64 PNG, nullable)
    FALSE,
    CURRENT_TIMESTAMP
) RETURNING id, booking_id, ticket_type_id, ticket_number, qr_code_data, qr_code_image, is_checked_in, checked_in_at, created_at, deleted_at
`

type CreateTicketParams struct {
	ID           pgtype.UUID `json:"id"`
	BookingID    pgtype.UUID `json:"booking_id"`
	TicketTypeID pgtype.UUID `json:"ticket_type_id"`
	TicketNumber string      `json:"ticket_number"`
	QrCodeData   string      `json:"qr_code_data"`
	QrCodeImage  pgtype.Text `json:"qr_code_image"`
}

// Ticket Operations
// Creates a new ticket record after a booking is confirmed.
func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.ID,
		arg.BookingID,
		arg.TicketTypeID,
		arg.TicketNumber,
		arg.QrCodeData,
		arg.QrCodeImage,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.TicketTypeID,
		&i.TicketNumber,
		&i.QrCodeData,
		&i.QrCodeImage,
		&i.IsCheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLatestTicketNumberSeq = `-- name: GetLatestTicketNumberSeq :one
SELECT ticket_number FROM tickets
WHERE ticket_number LIKE $1
ORDER BY created_at DESC
LIMIT 1
`

// Returns the highest-numbered ticket in the system for sequential numbering.
func (q *Queries) GetLatestTicketNumberSeq(ctx context.Context, ticketNumber string) (string, error) {
	row := q.db.QueryRow(ctx, getLatestTicketNumberSeq, ticketNumber)
	var ticket_number string
	err := row.Scan(&ticket_number)
	return ticket_number, err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, booking_id, ticket_type_id, ticket_number, qr_code_data, qr_code_image, is_checked_in, checked_in_at, created_at, deleted_at FROM tickets
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTicketByID(ctx context.Context, id pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.TicketTypeID,
		&i.TicketNumber,
		&i.QrCodeData,
		&i.QrCodeImage,
		&i.IsCheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTicketByNumber = `-- name: GetTicketByNumber :one
SELECT id, booking_id, ticket_type_id, ticket_number, qr_code_data, qr_code_image, is_checked_in, checked_in_at, created_at, deleted_at FROM tickets
WHERE ticket_number = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTicketByNumber(ctx context.Context, ticketNumber string) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByNumber, ticketNumber)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.TicketTypeID,
		&i.TicketNumber,
		&i.QrCodeData,
		&i.QrCodeImage,
		&i.IsCheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTicketByQRData = `-- name: GetTicketByQRData :one
SELECT id, booking_id, ticket_type_id, ticket_number, qr_code_data, qr_code_image, is_checked_in, checked_in_at, created_at, deleted_at FROM tickets
WHERE qr_code_data = $1 AND deleted_at IS NULL
`

// Retrieves a ticket by its unique QR payload string (used during check-in validation).
func (q *Queries) GetTicketByQRData(ctx context.Context, qrCodeData string) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByQRData, qrCodeData)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.TicketTypeID,
		&i.TicketNumber,
		&i.QrCodeData,
		&i.QrCodeImage,
		&i.IsCheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTicketsByBookingID = `-- name: GetTicketsByBookingID :many
SELECT t.id, t.booking_id, t.ticket_type_id, t.ticket_number, t.qr_code_data, t.qr_code_image, t.is_checked_in, t.checked_in_at, t.created_at, t.deleted_at, tt.name AS ticket_type_name
FROM tickets t
JOIN ticket_types tt ON t.ticket_type_id = tt.id
WHERE t.booking_id = $1 AND t.deleted_at IS NULL
ORDER BY t.created_at ASC
`

type GetTicketsByBookingIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	BookingID      pgtype.UUID        `json:"booking_id"`
	TicketTypeID   pgtype.UUID        `json:"ticket_type_id"`
	TicketNumber   string             `json:"ticket_number"`
	QrCodeData     string             `json:"qr_code_data"`
	QrCodeImage    pgtype.Text        `json:"qr_code_image"`
	IsCheckedIn    bool               `json:"is_checked_in"`
	CheckedInAt    pgtype.Timestamptz `json:"checked_in_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	TicketTypeName string             `json:"ticket_type_name"`
}

func (q *Queries) GetTicketsByBookingID(ctx context.Context, bookingID pgtype.UUID) ([]GetTicketsByBookingIDRow, error) {
	rows, err := q.db.Query(ctx, getTicketsByBookingID, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTicketsByBookingIDRow
	for rows.Next() {
		var i GetTicketsByBookingIDRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.TicketTypeID,
			&i.TicketNumber,
			&i.QrCodeData,
			&i.QrCodeImage,
			&i.IsCheckedIn,
			&i.CheckedInAt,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.TicketTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTicketCheckedIn = `-- name: MarkTicketCheckedIn :one
UPDATE tickets
SET is_checked_in = TRUE,
    checked_in_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, booking_id, ticket_type_id, ticket_number, qr_code_data, qr_code_image, is_checked_in, checked_in_at, created_at, deleted_at
`

// Marks a ticket as checked-in and records the timestamp.
func (q *Queries) MarkTicketCheckedIn(ctx context.Context, id pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, markTicketCheckedIn, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.TicketTypeID,
		&i.TicketNumber,
		&i.QrCodeData,
		&i.QrCodeImage,
		&i.IsCheckedIn,
		&i.CheckedInAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
