-- Add organizer and contact information fields to events table
ALTER TABLE events
ADD COLUMN organizer_name VARCHAR(255),
ADD COLUMN organizer_email VARCHAR(255),
ADD COLUMN organizer_phone VARCHAR(50),
ADD COLUMN organization VARCHAR(255),
ADD COLUMN contact_email VARCHAR(255),
ADD COLUMN contact_phone VARCHAR(50),
ADD COLUMN refund_policy TEXT,
ADD COLUMN terms_and_conditions TEXT,
ADD COLUMN event_type VARCHAR(50) DEFAULT 'CONFERENCE',
ADD COLUMN category VARCHAR(50) DEFAULT 'TECHNOLOGY',
ADD COLUMN max_tickets_per_user INTEGER DEFAULT 10,
ADD COLUMN booking_start_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN booking_end_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN tags TEXT[] DEFAULT '{}',
ADD COLUMN website_url VARCHAR(500),
ADD COLUMN facebook_url VARCHAR(500),
ADD COLUMN twitter_url VARCHAR(500),
ADD COLUMN instagram_url VARCHAR(500),
ADD COLUMN linkedin_url VARCHAR(500),
ADD COLUMN venue_name VARCHAR(255),
ADD COLUMN address_line1 VARCHAR(255),
ADD COLUMN address_line2 VARCHAR(255),
ADD COLUMN city VARCHAR(100),
ADD COLUMN state VARCHAR(100),
ADD COLUMN postal_code VARCHAR(20),
ADD COLUMN country VARCHAR(100) DEFAULT 'USA',
ADD COLUMN latitude DECIMAL(10, 8),
ADD COLUMN longitude DECIMAL(11, 8);
