-- SUPER_USER ROLES
CREATE TYPE SUPER_USER_ROLE AS ENUM (
    'SUPER_ADMIN',
    'ADMIN',
    'EDITOR'
);

-- SUPER_USER PERMISSIONS
CREATE TYPE PERMISSIONS AS ENUM (
    'MANAGE_EVENTS',
    'CREATE_EVENT',
    'EDIT_EVENT',
    'DELETE_EVENT',
    'VIEW_EVENT',
    'MANAGE_BOOKINGS',
    'CREATE_BOOKING',
    'EDIT_BOOKING',
    'DELETE_BOOKING',
    'VIEW_BOOKING',
    'MANAGE_USERS',
    'VIEW_REPORTS'
);

-- SUPER_USERS
CREATE TABLE IF NOT EXISTS super_users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role SUPER_USER_ROLE NOT NULL,
    permissions PERMISSIONS[] NOT NULL DEFAULT ARRAY['CREATE_EVENT', 'MANAGE_BOOKINGS']::PERMISSIONS[],
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
