package payment

import (
	"bytes"
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"net/http"
	"time"

	"github.com/dtg-lucifer/everato/internal/utils"
	"github.com/dtg-lucifer/everato/pkg"
)

// RazorpayProvider implements PaymentGateway for Razorpay.
type RazorpayProvider struct {
	KeyID         string
	KeySecret     string
	WebhookSecret string
	Currency      string
	HTTPClient    *http.Client
}

// NewRazorpayProvider initializes a Razorpay client, validating required environment variables.
func NewRazorpayProvider(currency string) (*RazorpayProvider, error) {
	keyID := utils.GetEnv("RAZORPAY_KEY_ID", "")
	keySecret := utils.GetEnv("RAZORPAY_KEY_SECRET", "")
	webhookSecret := utils.GetEnv("RAZORPAY_WEBHOOK_SECRET", "")

	var missing []string
	if keyID == "" {
		missing = append(missing, "RAZORPAY_KEY_ID")
	}
	if keySecret == "" {
		missing = append(missing, "RAZORPAY_KEY_SECRET")
	}

	if len(missing) > 0 {
		return nil, fmt.Errorf(
			"Razorpay selected as payment provider, but required environment variables are missing: %v. Please add them to your .env file or environment",
			missing,
		)
	}

	if currency == "" {
		currency = "INR"
	}

	return &RazorpayProvider{
		KeyID:         keyID,
		KeySecret:     keySecret,
		WebhookSecret: webhookSecret,
		Currency:      currency,
		HTTPClient:    &http.Client{Timeout: 15 * time.Second},
	}, nil
}

func (r *RazorpayProvider) GetProvider() ProviderType {
	return ProviderRazorpay
}

// CreateOrder calls Razorpay Orders API: POST https://api.razorpay.com/v1/orders
func (r *RazorpayProvider) CreateOrder(ctx context.Context, req CreateOrderRequest) (*CreateOrderResponse, error) {
	logger := pkg.NewLogger()
	defer logger.Close()

	// Convert major units to subunits (paise for INR)
	amountInSubunits := int(math.Round(req.Amount * 100))

	currency := req.Currency
	if currency == "" {
		currency = r.Currency
	}

	receipt := req.Receipt
	if receipt == "" {
		receipt = req.BookingID
	}
	// Razorpay receipt max length is 40 chars
	if len(receipt) > 40 {
		receipt = receipt[:40]
	}

	requestPayload := map[string]any{
		"amount":   amountInSubunits,
		"currency": currency,
		"receipt":  receipt,
		"notes": map[string]string{
			"booking_id":     req.BookingID,
			"customer_name":  req.CustomerName,
			"customer_email": req.CustomerEmail,
		},
	}

	bodyBytes, err := json.Marshal(requestPayload)
	if err != nil {
		return nil, fmt.Errorf("marshal razorpay order payload: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, "https://api.razorpay.com/v1/orders", bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, fmt.Errorf("create razorpay http request: %w", err)
	}

	httpReq.SetBasicAuth(r.KeyID, r.KeySecret)
	httpReq.Header.Set("Content-Type", "application/json")

	resp, err := r.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute razorpay order request: %w", err)
	}
	defer resp.Body.Close()

	respBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read razorpay response: %w", err)
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		logger.Error("Razorpay order creation failed", "status", resp.StatusCode, "body", string(respBytes))
		return nil, fmt.Errorf("razorpay error (%d): %s", resp.StatusCode, string(respBytes))
	}

	var parsed struct {
		ID       string `json:"id"`
		Amount   int    `json:"amount"`
		Currency string `json:"currency"`
		Status   string `json:"status"`
	}
	if err := json.Unmarshal(respBytes, &parsed); err != nil {
		return nil, fmt.Errorf("unmarshal razorpay order response: %w", err)
	}

	return &CreateOrderResponse{
		OrderID:  parsed.ID,
		Provider: string(ProviderRazorpay),
		Amount:   req.Amount,
		Currency: parsed.Currency,
		KeyID:    r.KeyID,
		Metadata: map[string]string{
			"receipt": receipt,
		},
	}, nil
}

// VerifyPayment checks the HMAC-SHA256 signature generated by Razorpay Checkout.
// Signature = HMAC_SHA256(order_id + "|" + payment_id, key_secret)
func (r *RazorpayProvider) VerifyPayment(ctx context.Context, req VerifyPaymentRequest) (*VerifyPaymentResponse, error) {
	if req.OrderID == "" || req.PaymentID == "" || req.Signature == "" {
		return nil, fmt.Errorf("order_id, payment_id, and signature are required for Razorpay verification")
	}

	data := fmt.Sprintf("%s|%s", req.OrderID, req.PaymentID)
	mac := hmac.New(sha256.New, []byte(r.KeySecret))
	mac.Write([]byte(data))
	expectedSignature := hex.EncodeToString(mac.Sum(nil))

	if !hmac.Equal([]byte(req.Signature), []byte(expectedSignature)) {
		return &VerifyPaymentResponse{
			Success:   false,
			PaymentID: req.PaymentID,
			OrderID:   req.OrderID,
			Message:   "Invalid Razorpay payment signature - verification failed",
		}, fmt.Errorf("signature verification failed")
	}

	return &VerifyPaymentResponse{
		Success:   true,
		PaymentID: req.PaymentID,
		OrderID:   req.OrderID,
		Message:   "Payment signature verified successfully",
	}, nil
}

// HandleWebhook verifies and decodes Razorpay webhook notifications.
func (r *RazorpayProvider) HandleWebhook(ctx context.Context, body []byte, signature string) (*WebhookEvent, error) {
	if r.WebhookSecret != "" {
		mac := hmac.New(sha256.New, []byte(r.WebhookSecret))
		mac.Write(body)
		expected := hex.EncodeToString(mac.Sum(nil))
		if !hmac.Equal([]byte(signature), []byte(expected)) {
			return nil, fmt.Errorf("invalid razorpay webhook signature")
		}
	}

	var payload struct {
		Event   string `json:"event"`
		Payload struct {
			Payment struct {
				Entity struct {
					ID      string            `json:"id"`
					OrderID string            `json:"order_id"`
					Status  string            `json:"status"`
					Notes   map[string]string `json:"notes"`
				} `json:"entity"`
			} `json:"payment"`
		} `json:"payload"`
	}

	if err := json.Unmarshal(body, &payload); err != nil {
		return nil, fmt.Errorf("unmarshal razorpay webhook: %w", err)
	}

	status := "FAILED"
	if payload.Event == "payment.captured" || payload.Payload.Payment.Entity.Status == "captured" {
		status = "SUCCESS"
	}

	return &WebhookEvent{
		EventType: payload.Event,
		OrderID:   payload.Payload.Payment.Entity.OrderID,
		PaymentID: payload.Payload.Payment.Entity.ID,
		BookingID: payload.Payload.Payment.Entity.Notes["booking_id"],
		Status:    status,
		RawBody:   body,
	}, nil
}

func (r *RazorpayProvider) GetClientConfig() map[string]string {
	return map[string]string{
		"provider": string(ProviderRazorpay),
		"key_id":   r.KeyID,
		"currency": r.Currency,
	}
}
