-- PAYMENTS
DROP TABLE IF EXISTS payments;

-- TICKETS
DROP TABLE IF EXISTS tickets;

-- BOOKINGS
DROP TABLE IF EXISTS bookings;

-- COUPONS
DROP TABLE IF EXISTS coupons;

-- TICKET_TYPE
DROP TABLE IF EXISTS ticket_types;
