-- Drop the UUID extension
DROP EXTENSION IF EXISTS "uuid-ossp";

-- Drop the tables in reverse order of creation
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS users;

-- Drop the enums
DROP TYPE IF EXISTS BOOKING_STATUS;
DROP TYPE IF EXISTS PAYMENT_STATUS;
DROP TYPE IF EXISTS TICKET_STATUS;
DROP TYPE IF EXISTS PAYMENT_TYPE;
