-- Enable extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ENUM TYPES
CREATE TYPE BOOKING_STATUS AS ENUM (
    'PENDING',
    'PENDING_PAYMENT',
    'TIMEOUT',
    'FILLED',
    'CONFIRMED',
    'CANCELLED'
);

CREATE TYPE PAYMENT_STATUS AS ENUM (
    'DONE',
    'CANCELLED',
    'TIMEOUT',
    'FAILED',
    'REJECTED'
);

CREATE TYPE TICKET_STATUS AS ENUM (
    'BOOKED',
    'CANCELLED',
    'TIMEOUT',
    'FAILED'
);

CREATE TYPE PAYMENT_TYPE AS ENUM (
    'UPI_SS',
    'GATEWAY'
);

-- USERS
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- EVENTS
CREATE TABLE IF NOT EXISTS events (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    banner TEXT NOT NULL,
    icon TEXT NOT NULL,
    admin_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    location TEXT,
    total_seats INT NOT NULL,
    available_seats INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
